version: '3.7'
services:
  app:
    build:
      context: .
    env_file: ./.env.prod.local
    volumes:
      - ../data/tmp:/usr/src/app/data/tmp
      - ../data/proposals:/usr/src/app/data/proposals
      - ../data/staging:/usr/src/app/data/staging
    depends_on: 
      - redis
      - db
    ports: 
      - 5000:8080
    entrypoint: npm start
  redis:
    image: redis:5.0
    volumes:
      - memdata:/data
  db:
    image: postgres:11.0
    environment:
      POSTGRES_PASSWORD: rushcoderpwd
      POSTGRES_USER: rushcoderuser
      POSTGRES_DB: rushcoder
      PGDATA: /var/lib/postgresql/data/local
    volumes:
      - dbdata:/var/lib/postgresql/data/local/

volumes:
  dbdata:
  memdata: